apiVersion: apps/v1
kind: Deployment

metadata:
  name: addressbook
spec:
  replicas: 3
  minReadySeconds: 10   # wait for 10 sec before going to deploy next pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # max pods that can be unavailable
      maxSurge: 1        # max number of pods to run for the deployment

  selector:
    matchLabels:
      app: addressbook

  template:
    metadata:
      name: addressbook
      labels:
        app: addressbook
    spec:
      containers:
       - name: app
         image: nextcloud:22.0.0-apache
         #image: sonal04/addressbook:1

---
kind: Service
apiVersion: v1
metadata:
   name: addressbook-svc
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30001
  selector:
    app: addressbook
